[page]
title = "pymd"
date = "2026-08-09"
navigation = [
    {name = "Home", link = "../index.html"}
]

[content]
body = '''

<div class="textbox" markdown="1">
# Pymd

This is a project page about __pymd__

</div>
'''
