[page]
title = "pymd"
date = "2026-08-09"
navigation = [
    {name = "Home", link = "../index.html"}
]

[content]
body = '''

<div class="textbox" markdown="1">
# Pymd

For my computer science classes involving code, I take notes in __Markdown__ so I can format both notes and code segments, and so I can upload it to GitHub for easy sharing and remote access. As of now, my editor of choice is __Neovim__, and I wanted a terminal application to view my formatted Markdown.

__Pymd__ is a simple Markdown viewer. Written in __Python__, it uses the __ncurses__ library to render Markdown files to the terminal.

<br>

Currently, __pymd__ has the capabilities to

- Notate different header levels with color
- Bold and Italics
- In-text `code sections`

<br>

Future planned additions include

- Hot reloading
- Fenced code blocks
- Horizontal Rules 

<br>

__You can find pymd at [my GitHub](https://github.com/whgriff05/pymd/)__

</div>
'''
